# filebeat.yml

filebeat.inputs:
- type: docker
  combine_partial: true
  containers:
    path: "/var/lib/docker/containers"
    stream: all
    ids:
      - "*"
    json:
      keys_under_root: true
      message_key: log
      add_error_key: true
      ignore_decoding_error: true
    exclude_files: ['\.gz$']
    ignore_older: "7d"
    close_inactive: "1m"
    tags: ['json','docker']

# filebeat.config.modules:
#   path: ${path.config}/modules.d/*.yml
#   reload.enabled: false

# setup.template.settings:
#   index.number_of_shards: 3
  
# setup.kibana:
# # if your kibana is local you can change it to 127.0.0.1:80
#   host: "10.110.4.100:80"
#   protocol: "http"
# # identification required for X-pack  
#   username: "my_login"
#   password: "my_password"
# # path needed if kibana not at website root  
#   path: "/kibana"

output.logstash:
# if your elasticsearch is local you can change it to 127.0.0.1:9200
  hosts: ["127.0.0.1:9200"]
  # template:
  #   name: "filebeat"
  #   path: "fields.yml"
  #   overwrite: false
  # protocol: "http"

# Write Filebeat own logs only to file to avoid catching them with itself in docker log files
logging.to_files: true
logging.to_syslog: false
