# filebeat.yml

filebeat.inputs:
- type: docker
  combine_partial: true
  containers:
    path: "/var/lib/docker/containers"
    stream: all
    ids:
      - "*"
  json:
    keys_under_root: true
    message_key: log
    add_error_key: true
    ignore_decoding_error: true
  encoding: "utf-8"
  exclude_files: ['\.gz$']
  ignore_older: "1m"
  close_inactive: "1m"
  tags: ['json','docker']
  processors:
  - add_docker_metadata: ~
processors:
  - drop_fields:
      when:
        has_fields: ['host']
      fields: ['host']
  - drop_fields:
      when:
        has_fields: ['stream']
      fields: ['stream']
  - drop_fields:
      when:
        has_fields: ['source']
      fields: ['source']
  - drop_fields:
      when:
        has_fields: ['@t']
      fields: ['@t']

# filebeat.config.modules:
#   path: ${path.config}/modules.d/*.yml
#   reload.enabled: false

# setup.template.settings:
#   index.number_of_shards: 3
  
# setup.kibana:
# # if your kibana is local you can change it to 127.0.0.1:80
#   host: "10.110.4.100:80"
#   protocol: "http"
# # identification required for X-pack  
#   username: "my_login"
#   password: "my_password"
# # path needed if kibana not at website root  
#   path: "/kibana"

output.logstash:
# output to logstash beats input, you'll have to setup this IP in case you want to ship to an other server.
  hosts: ["logstash:5044"]
  # template:
  #   name: "filebeat"
  #   path: "fields.yml"
  #   overwrite: false
  # protocol: "http"

# Write Filebeat own logs only to file to avoid catching them with itself in docker log files
logging.to_files: true
logging.to_syslog: false
